vich_uploader:
    db_driver: orm

    mappings:
        pictureJumbotron:
            uri_prefix: /uploads/jumbotron
            upload_destination: '%kernel.project_dir%/public/uploads/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
        
        picturePlatsforms:
            uri_prefix: /uploads/platsforms
            upload_destination: '%kernel.project_dir%/public/uploads/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
